params:
  tcn_ae:
    n_epochs: 50
    lr: 0.04
    enc_channels: [2, 4]
    hidden_dim: 8
    dec_channels: [4, 2]
    dilation_base: 2
    kernel_size: 6
    batch_size: 16
    train_window_len: 2048
    checkpoints_dir: "checkpoints/"
